# Generated by Django 5.1.2 on 2024-11-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_reward_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the reward', null=True, upload_to='reward_images/'),
        ),
    ]
